minkei/home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
]

minkei/intro_econ/urls.py
from django.urls import path
from .views import EconArticleListView, IntroEconArticle

app_name = 'intro_econ'

urlpatterns = [
    path('', EconArticleListView, name='intro_econ_list'),
    path('<slug:slug>/', IntroEconArticle, name='intro_econ_article'),
]

minkei/intro_macroecon/urls.py
# intro_macroecon/urls.py
from django.urls import path
from .views import MacroEconArticleListView, IntroMacroEconArticle

app_name = 'intro_macroecon'

urlpatterns = [
    path('', MacroEconArticleListView, name='intro_macroecon_list'),
    path('<slug:slug>/', IntroMacroEconArticle, name='intro_macroecon_article'),
]

minkei/intro_metrics/urls.py
from django.urls import path
from .views import MetricsArticleListView, IntroMetricsArticle

app_name = 'intro_metrics'

urlpatterns = [
    path('', MetricsArticleListView, name='intro_metrics_list'),
    path('<slug:slug>/', IntroMetricsArticle, name='intro_metrics_article'),
]

minkei/intro_microecon/urls.py
from django.urls import path
from .views import MicroEconArticleListView, MicroEconArticleDetail

app_name = 'intro_microecon'

urlpatterns = [
    path('', MicroEconArticleListView, name='intro_microecon_list'),
    path('<slug:slug>/', MicroEconArticleDetail, name='intro_microecon_article'),
]

minkei/minkei/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),                                             # ホームページ
    path("prof/", include("prof.urls")),                                        # プロフィール
    path('beginning/', include('beginning.urls')),                              # はじめに
    path('markdownx/', include('markdownx.urls')),                              # マークダウン記法に関するURL 
    path("roadmap/", include("roadmap.urls")),                                  # 経済学のロードマップ
    path('intro-econ/', include('intro_econ.urls', namespace='intro_econ')),    # 経済学 入門（講義）
    path('intro-microecon/', include('intro_microecon.urls')),                  # ミクロ経済学 入門（講義）
    path('advanced_microecon/', include('advanced_microecon.urls')),            # ミクロ経済学 応用（講義）
    path('intro-macroecon/', include('intro_macroecon.urls')),                  # マクロ経済学 入門（講義）
    path('advanced-macroecon/', include('advanced_macroecon.urls')),            # マクロ経済学 応用（講義）
    path('intro-metrics/', include('intro_metrics.urls')),                      # 計量経済学 入門（講義）
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

minkei/home/models.py
from django.db import models

# Create your models here.

minkei/home/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home/home.html')

minkei/templates/home/home.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}ホーム - みんなの経済学！（みんけい！）{% endblock %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
{% endblock %}

{% block content %}
    <!-- メインボディ -->
    <section>
        <h2>まずはここから！</h2>
        <div class="button-container">
            <a href="{% url 'beginning' %}"><button>はじめに・・・</button></a>
            <a href="{% url 'roadmap' %}"><button>経済学のロードマップ</button></a>
            <a href="{% url 'intro_econ:intro_econ_list' %}"><button>経済学入門（講義）</button></a>
        </div>
    </section>

    <section>
        <h2>ミクロ経済学</h2>
        <div class="button-container">
            <a href="{% url 'intro_microecon:intro_microecon_list' %}"><button>ミクロ経済学 入門（講義）</button></a>
            <a href="{% url 'advanced_microecon:advanced_microecon_list' %}"><button>ミクロ経済学 応用（講義）</button></a>
        </div>
    </section>

    <section>
        <h2>マクロ経済学</h2>
        <div class="button-container">
            <a href="{% url 'intro_macroecon:intro_macroecon_list' %}"><button>マクロ経済学 入門（講義）</button></a>
            <a href="{% url 'advanced_macroecon:advanced_macroecon_list' %}"><button>マクロ経済学 応用（講義）</button></a>
        </div>
    </section>

    <section>
        <h2>計量経済学</h2>
        <div class="button-container">
            <a href="{% url 'intro_metrics:intro_metrics_list' %}"><button>計量経済学 入門（講義）</button></a>
            <button>計量経済学 応用（講義）</button>
        </div>
    </section>

    <section>
        <h2>経済史</h2>
        <div class="button-container">
            <button>経済史 入門（講義）</button>
            <button>経済史 応用（講義）</button>
        </div>
    </section>

    <section>
        <h2>その他</h2>
        <div class="button-container">
            <button>各応用分野について</button>
            <button>大学で経済学を学ぶ</button>
            <button>経済学検定について</button>
            <button>質問・お問い合わせ</button>
        </div>
    </section>
{% endblock %}